// ============================================================
// AUTO-GENERATED by nim-ffi v0.1.3  (ffiMode=cbor, ffiLang=rust). DO NOT EDIT.
//
//   Source:     ../timer.nim
//   Generator:  ffi/codegen/rust.nim
//   Regenerate: nimble genbindings_rust_cbor
// ============================================================

mod ffi;
mod types;
mod api;
pub use types::*;
pub use api::*;
