// Generated by nim-ffi Kotlin codegen. Do not edit by hand.
package org.logos.mytimer

/** Typed result mirroring the library's EchoResponse. */
data class EchoResponse(val echoed: String, val timerName: String)

class MyTimerNode(name: String) : AutoCloseable {
    private val ctx: Long = nativeCreate(name)

    fun echo(message: String, delayMs: Long = 0): EchoResponse {
        val a = nativeEcho(ctx, message, delayMs)
        return EchoResponse(a[0], a[1])
    }
    fun version(): String = nativeVersion(ctx)
    override fun close() = nativeDestroy(ctx)

    private external fun nativeCreate(name: String): Long
    private external fun nativeEcho(ctx: Long, message: String, delayMs: Long): Array<String>
    private external fun nativeVersion(ctx: Long): String
    private external fun nativeDestroy(ctx: Long)

    companion object {
        init {
            System.loadLibrary("my_timer")
            System.loadLibrary("my_timer_jni")
        }
    }
}