// Generated by nim-ffi native Rust codegen. Do not edit by hand.
#![allow(dead_code)]
use std::os::raw::{c_char, c_int, c_void};
use std::sync::mpsc::{sync_channel, SyncSender};
use super::ffi;
use super::types::*;

const RET_OK: c_int = 0;

unsafe fn err_text(msg: *const c_char, len: usize) -> String {
    if msg.is_null() || len == 0 { return String::from("error"); }
    String::from_utf8_lossy(std::slice::from_raw_parts(msg as *const u8, len)).into_owned()
}

unsafe extern "C" fn ack_cb(ret: c_int, msg: *const c_char, len: usize, ud: *mut c_void) {
    let tx = Box::from_raw(ud as *mut SyncSender<Result<(), String>>);
    let _ = tx.send(if ret == RET_OK { Ok(()) } else { Err(err_text(msg, len)) });
}
unsafe extern "C" fn str_cb(ret: c_int, msg: *const c_char, len: usize, ud: *mut c_void) {
    let tx = Box::from_raw(ud as *mut SyncSender<Result<String, String>>);
    let r = if ret == RET_OK {
        let b = if msg.is_null() || len == 0 { Vec::new() } else { std::slice::from_raw_parts(msg as *const u8, len).to_vec() };
        Ok(String::from_utf8_lossy(&b).into_owned())
    } else { Err(err_text(msg, len)) };
    let _ = tx.send(r);
}
unsafe extern "C" fn cb_my_timer_echo(ret: c_int, msg: *const c_char, len: usize, ud: *mut c_void) {
    let tx = Box::from_raw(ud as *mut SyncSender<Result<EchoResponse, String>>);
    let r = if ret == RET_OK && !msg.is_null() {
        Ok(EchoResponse::from_c(&*(msg as *const ffi::EchoResponse)))
    } else { Err(err_text(msg, len)) };
    let _ = tx.send(r);
}

pub struct MyTimerNode { ctx: *mut c_void }
unsafe impl Send for MyTimerNode {}
unsafe impl Sync for MyTimerNode {}

impl MyTimerNode {
    pub fn new(config: TimerConfig) -> Result<Self, String> {
        let mut strings = Vec::new();
        let c_config = config.to_c_inner(&mut strings);
        let (tx, rx) = sync_channel::<Result<(), String>>(1);
        let raw = Box::into_raw(Box::new(tx)) as *mut c_void;
        let ctx = unsafe { ffi::my_timer_create(c_config, ack_cb, raw) };
        let res = rx.recv().map_err(|_| String::from("callback channel closed"))?;
        res?;
        if ctx.is_null() { return Err(String::from("my_timer_create returned null")); }
        let _ = strings;
        Ok(MyTimerNode { ctx })
    }

    pub fn echo(&self, req: EchoRequest) -> Result<EchoResponse, String> {
        let mut strings = Vec::new();
        let c_req = req.to_c_inner(&mut strings);
        let (tx, rx) = sync_channel::<Result<EchoResponse, String>>(1);
        let raw = Box::into_raw(Box::new(tx)) as *mut c_void;
        let rc = unsafe { ffi::my_timer_echo(self.ctx, cb_my_timer_echo, raw, c_req) };
        if rc != RET_OK {
            drop(unsafe { Box::from_raw(raw as *mut SyncSender<Result<EchoResponse, String>>) });
            return Err(String::from("my_timer_echo dispatch failed"));
        }
        let _ = strings;
        rx.recv().map_err(|_| String::from("callback channel closed"))?
    }

    pub fn version(&self) -> Result<String, String> {
        let (tx, rx) = sync_channel::<Result<String, String>>(1);
        let raw = Box::into_raw(Box::new(tx)) as *mut c_void;
        let rc = unsafe { ffi::my_timer_version(self.ctx, str_cb, raw) };
        if rc != RET_OK {
            drop(unsafe { Box::from_raw(raw as *mut SyncSender<Result<String, String>>) });
            return Err(String::from("my_timer_version dispatch failed"));
        }
        rx.recv().map_err(|_| String::from("callback channel closed"))?
    }

    // SKIPPED my_timer_complex: seq/Option params not yet supported by native Rust codegen
    // SKIPPED my_timer_schedule: seq/Option params not yet supported by native Rust codegen
}

impl Drop for MyTimerNode {
    fn drop(&mut self) { unsafe { ffi::my_timer_destroy(self.ctx); } }
}