// Generated by nim-ffi native Rust codegen. Do not edit by hand.
#![allow(dead_code)]
use std::os::raw::{c_char, c_int, c_void};
use std::sync::mpsc::{sync_channel, SyncSender};
use super::ffi;
use super::types::*;

const RET_OK: c_int = 0;

unsafe fn err_text(msg: *const c_char, len: usize) -> String {
    if msg.is_null() || len == 0 { return String::from("error"); }
    String::from_utf8_lossy(std::slice::from_raw_parts(msg as *const u8, len)).into_owned()
}

unsafe extern "C" fn ack_cb(ret: c_int, msg: *const c_char, len: usize, ud: *mut c_void) {
    let tx = Box::from_raw(ud as *mut SyncSender<Result<(), String>>);
    let _ = tx.send(if ret == RET_OK { Ok(()) } else { Err(err_text(msg, len)) });
}
unsafe extern "C" fn str_cb(ret: c_int, msg: *const c_char, len: usize, ud: *mut c_void) {
    let tx = Box::from_raw(ud as *mut SyncSender<Result<String, String>>);
    let r = if ret == RET_OK {
        let b = if msg.is_null() || len == 0 { Vec::new() } else { std::slice::from_raw_parts(msg as *const u8, len).to_vec() };
        Ok(String::from_utf8_lossy(&b).into_owned())
    } else { Err(err_text(msg, len)) };
    let _ = tx.send(r);
}
unsafe extern "C" fn cb_my_timer_echo(ret: c_int, msg: *const c_char, len: usize, ud: *mut c_void) {
    let tx = Box::from_raw(ud as *mut SyncSender<Result<EchoResponse, String>>);
    let r = if ret == RET_OK && !msg.is_null() {
        Ok(EchoResponse::from_c(&*(msg as *const ffi::EchoResponse)))
    } else { Err(err_text(msg, len)) };
    let _ = tx.send(r);
}
unsafe extern "C" fn cb_my_timer_complex(ret: c_int, msg: *const c_char, len: usize, ud: *mut c_void) {
    let tx = Box::from_raw(ud as *mut SyncSender<Result<ComplexResponse, String>>);
    let r = if ret == RET_OK && !msg.is_null() {
        Ok(ComplexResponse::from_c(&*(msg as *const ffi::ComplexResponse)))
    } else { Err(err_text(msg, len)) };
    let _ = tx.send(r);
}
unsafe extern "C" fn cb_my_timer_schedule(ret: c_int, msg: *const c_char, len: usize, ud: *mut c_void) {
    let tx = Box::from_raw(ud as *mut SyncSender<Result<ScheduleResult, String>>);
    let r = if ret == RET_OK && !msg.is_null() {
        Ok(ScheduleResult::from_c(&*(msg as *const ffi::ScheduleResult)))
    } else { Err(err_text(msg, len)) };
    let _ = tx.send(r);
}

struct OnEchoFiredHandler { f: Box<dyn Fn(&EchoEvent) + Send + Sync> }
unsafe extern "C" fn on_echo_fired_trampoline(ret: c_int, msg: *const c_char, _len: usize, ud: *mut c_void) {
    if ud.is_null() || ret != RET_OK || msg.is_null() { return; }
    let h = &*(ud as *const OnEchoFiredHandler);
    (h.f)(&EchoEvent::from_c(&*(msg as *const ffi::EchoEvent)));
}

#[derive(Clone, Copy)]
pub struct ListenerHandle { pub id: u64 }

pub struct MyTimerNode {
    ctx: *mut c_void,
    listeners: std::sync::Mutex<std::collections::HashMap<u64, Box<dyn std::any::Any + Send>>>,
}
unsafe impl Send for MyTimerNode {}
unsafe impl Sync for MyTimerNode {}

impl MyTimerNode {
    pub fn new(config: TimerConfig) -> Result<Self, String> {
        let c_config = config.to_c();
        let (tx, rx) = sync_channel::<Result<(), String>>(1);
        let raw = Box::into_raw(Box::new(tx)) as *mut c_void;
        let ctx = unsafe { ffi::my_timer_create(c_config.c, ack_cb, raw) };
        let res = rx.recv().map_err(|_| String::from("callback channel closed"))?;
        res?;
        if ctx.is_null() { return Err(String::from("my_timer_create returned null")); }
        Ok(MyTimerNode { ctx, listeners: std::sync::Mutex::new(std::collections::HashMap::new()) })
    }

    pub fn echo(&self, req: EchoRequest) -> Result<EchoResponse, String> {
        let c_req = req.to_c();
        let (tx, rx) = sync_channel::<Result<EchoResponse, String>>(1);
        let raw = Box::into_raw(Box::new(tx)) as *mut c_void;
        let rc = unsafe { ffi::my_timer_echo(self.ctx, cb_my_timer_echo, raw, c_req.c) };
        if rc != RET_OK {
            drop(unsafe { Box::from_raw(raw as *mut SyncSender<Result<EchoResponse, String>>) });
            return Err(String::from("my_timer_echo dispatch failed"));
        }
        rx.recv().map_err(|_| String::from("callback channel closed"))?
    }

    pub fn version(&self) -> Result<String, String> {
        let (tx, rx) = sync_channel::<Result<String, String>>(1);
        let raw = Box::into_raw(Box::new(tx)) as *mut c_void;
        let rc = unsafe { ffi::my_timer_version(self.ctx, str_cb, raw) };
        if rc != RET_OK {
            drop(unsafe { Box::from_raw(raw as *mut SyncSender<Result<String, String>>) });
            return Err(String::from("my_timer_version dispatch failed"));
        }
        rx.recv().map_err(|_| String::from("callback channel closed"))?
    }

    pub fn complex(&self, req: ComplexRequest) -> Result<ComplexResponse, String> {
        let c_req = req.to_c();
        let (tx, rx) = sync_channel::<Result<ComplexResponse, String>>(1);
        let raw = Box::into_raw(Box::new(tx)) as *mut c_void;
        let rc = unsafe { ffi::my_timer_complex(self.ctx, cb_my_timer_complex, raw, c_req.c) };
        if rc != RET_OK {
            drop(unsafe { Box::from_raw(raw as *mut SyncSender<Result<ComplexResponse, String>>) });
            return Err(String::from("my_timer_complex dispatch failed"));
        }
        rx.recv().map_err(|_| String::from("callback channel closed"))?
    }

    pub fn schedule(&self, job: JobSpec, retry: RetryPolicy, schedule: ScheduleConfig) -> Result<ScheduleResult, String> {
        let c_job = job.to_c();
        let c_retry = retry.to_c();
        let c_schedule = schedule.to_c();
        let (tx, rx) = sync_channel::<Result<ScheduleResult, String>>(1);
        let raw = Box::into_raw(Box::new(tx)) as *mut c_void;
        let rc = unsafe { ffi::my_timer_schedule(self.ctx, cb_my_timer_schedule, raw, c_job.c, c_retry.c, c_schedule.c) };
        if rc != RET_OK {
            drop(unsafe { Box::from_raw(raw as *mut SyncSender<Result<ScheduleResult, String>>) });
            return Err(String::from("my_timer_schedule dispatch failed"));
        }
        rx.recv().map_err(|_| String::from("callback channel closed"))?
    }

    pub fn add_on_echo_fired_listener<F>(&self, handler: F) -> ListenerHandle
    where F: Fn(&EchoEvent) + Send + Sync + 'static {
        let owned: Box<OnEchoFiredHandler> = Box::new(OnEchoFiredHandler { f: Box::new(handler) });
        let raw = &*owned as *const OnEchoFiredHandler as *mut c_void;
        let id = unsafe { ffi::my_timer_add_event_listener(self.ctx, b"on_echo_fired\0".as_ptr() as *const c_char, on_echo_fired_trampoline, raw) };
        if id != 0 { self.listeners.lock().unwrap().insert(id, owned as Box<dyn std::any::Any + Send>); }
        ListenerHandle { id }
    }

    pub fn remove_event_listener(&self, handle: ListenerHandle) -> bool {
        if handle.id == 0 { return false; }
        let rc = unsafe { ffi::my_timer_remove_event_listener(self.ctx, handle.id) };
        self.listeners.lock().unwrap().remove(&handle.id);
        rc == RET_OK
    }

}

impl Drop for MyTimerNode {
    fn drop(&mut self) { unsafe { ffi::my_timer_destroy(self.ctx); } }
}