// Generated by nim-ffi native Rust codegen. Do not edit by hand.
use std::ffi::{CStr, CString};
use std::os::raw::c_char;
use super::ffi;

fn cstr(p: *const c_char) -> String {
    if p.is_null() { String::new() }
    else { unsafe { CStr::from_ptr(p) }.to_string_lossy().into_owned() }
}

#[derive(Clone, Debug, Default)]
pub struct TimerConfig {
    pub name: String,
}

impl TimerConfig {
    pub fn to_c_inner(&self, strings: &mut Vec<CString>) -> ffi::TimerConfig {
        let name_c = CString::new(self.name.as_str()).unwrap_or_default();
        let name_p = name_c.as_ptr();
        strings.push(name_c);
        ffi::TimerConfig {
            name: name_p,
        }
    }
    pub fn from_c(c: &ffi::TimerConfig) -> Self {
        TimerConfig {
            name: cstr(c.name),
        }
    }
}

#[derive(Clone, Debug, Default)]
pub struct EchoRequest {
    pub message: String,
    pub delay_ms: i64,
}

impl EchoRequest {
    pub fn to_c_inner(&self, strings: &mut Vec<CString>) -> ffi::EchoRequest {
        let message_c = CString::new(self.message.as_str()).unwrap_or_default();
        let message_p = message_c.as_ptr();
        strings.push(message_c);
        ffi::EchoRequest {
            message: message_p,
            delay_ms: self.delay_ms,
        }
    }
    pub fn from_c(c: &ffi::EchoRequest) -> Self {
        EchoRequest {
            message: cstr(c.message),
            delay_ms: c.delay_ms,
        }
    }
}

#[derive(Clone, Debug, Default)]
pub struct EchoResponse {
    pub echoed: String,
    pub timer_name: String,
}

impl EchoResponse {
    pub fn to_c_inner(&self, strings: &mut Vec<CString>) -> ffi::EchoResponse {
        let echoed_c = CString::new(self.echoed.as_str()).unwrap_or_default();
        let echoed_p = echoed_c.as_ptr();
        strings.push(echoed_c);
        let timer_name_c = CString::new(self.timer_name.as_str()).unwrap_or_default();
        let timer_name_p = timer_name_c.as_ptr();
        strings.push(timer_name_c);
        ffi::EchoResponse {
            echoed: echoed_p,
            timer_name: timer_name_p,
        }
    }
    pub fn from_c(c: &ffi::EchoResponse) -> Self {
        EchoResponse {
            echoed: cstr(c.echoed),
            timer_name: cstr(c.timer_name),
        }
    }
}

#[derive(Clone, Debug, Default)]
pub struct ComplexResponse {
    pub summary: String,
    pub item_count: i64,
    pub has_note: bool,
}

impl ComplexResponse {
    pub fn to_c_inner(&self, strings: &mut Vec<CString>) -> ffi::ComplexResponse {
        let summary_c = CString::new(self.summary.as_str()).unwrap_or_default();
        let summary_p = summary_c.as_ptr();
        strings.push(summary_c);
        ffi::ComplexResponse {
            summary: summary_p,
            item_count: self.item_count,
            has_note: if self.has_note { 1 } else { 0 },
        }
    }
    pub fn from_c(c: &ffi::ComplexResponse) -> Self {
        ComplexResponse {
            summary: cstr(c.summary),
            item_count: c.item_count,
            has_note: c.has_note != 0,
        }
    }
}

#[derive(Clone, Debug, Default)]
pub struct EchoEvent {
    pub message: String,
    pub echo_count: i64,
}

impl EchoEvent {
    pub fn to_c_inner(&self, strings: &mut Vec<CString>) -> ffi::EchoEvent {
        let message_c = CString::new(self.message.as_str()).unwrap_or_default();
        let message_p = message_c.as_ptr();
        strings.push(message_c);
        ffi::EchoEvent {
            message: message_p,
            echo_count: self.echo_count,
        }
    }
    pub fn from_c(c: &ffi::EchoEvent) -> Self {
        EchoEvent {
            message: cstr(c.message),
            echo_count: c.echo_count,
        }
    }
}

#[derive(Clone, Debug, Default)]
pub struct ScheduleResult {
    pub job_id: String,
    pub will_run_count: i64,
    pub first_run_at_ms: i64,
    pub effective_backoff_ms: i64,
}

impl ScheduleResult {
    pub fn to_c_inner(&self, strings: &mut Vec<CString>) -> ffi::ScheduleResult {
        let job_id_c = CString::new(self.job_id.as_str()).unwrap_or_default();
        let job_id_p = job_id_c.as_ptr();
        strings.push(job_id_c);
        ffi::ScheduleResult {
            job_id: job_id_p,
            will_run_count: self.will_run_count,
            first_run_at_ms: self.first_run_at_ms,
            effective_backoff_ms: self.effective_backoff_ms,
        }
    }
    pub fn from_c(c: &ffi::ScheduleResult) -> Self {
        ScheduleResult {
            job_id: cstr(c.job_id),
            will_run_count: c.will_run_count,
            first_run_at_ms: c.first_run_at_ms,
            effective_backoff_ms: c.effective_backoff_ms,
        }
    }
}
