// Generated by nim-ffi native Rust codegen. Do not edit by hand.
#![allow(dead_code)]
use std::ffi::{CStr, CString};
use std::os::raw::c_char;
use super::ffi;

fn cstr(p: *const c_char) -> String {
    if p.is_null() { String::new() }
    else { unsafe { CStr::from_ptr(p) }.to_string_lossy().into_owned() }
}

#[derive(Clone, Debug, Default)]
pub struct TimerConfig {
    pub name: String,
}

pub struct TimerConfigC {
    pub c: ffi::TimerConfig,
    _s: Vec<CString>,
}

impl TimerConfig {
    pub fn to_c(&self) -> TimerConfigC {
        #[allow(unused_mut)]
        let mut h = TimerConfigC { c: unsafe { std::mem::zeroed() }, _s: Vec::new(),
        };
        { let cs = CString::new(self.name.as_str()).unwrap_or_default(); h.c.name = cs.as_ptr(); h._s.push(cs); }
        h
    }
    pub fn from_c(c: &ffi::TimerConfig) -> Self {
        TimerConfig {
            name: cstr(c.name),
        }
    }
}

#[derive(Clone, Debug, Default)]
pub struct EchoRequest {
    pub message: String,
    pub delay_ms: i64,
}

pub struct EchoRequestC {
    pub c: ffi::EchoRequest,
    _s: Vec<CString>,
}

impl EchoRequest {
    pub fn to_c(&self) -> EchoRequestC {
        #[allow(unused_mut)]
        let mut h = EchoRequestC { c: unsafe { std::mem::zeroed() }, _s: Vec::new(),
        };
        { let cs = CString::new(self.message.as_str()).unwrap_or_default(); h.c.message = cs.as_ptr(); h._s.push(cs); }
        h.c.delay_ms = self.delay_ms;
        h
    }
    pub fn from_c(c: &ffi::EchoRequest) -> Self {
        EchoRequest {
            message: cstr(c.message),
            delay_ms: c.delay_ms,
        }
    }
}

#[derive(Clone, Debug, Default)]
pub struct EchoResponse {
    pub echoed: String,
    pub timer_name: String,
}

pub struct EchoResponseC {
    pub c: ffi::EchoResponse,
    _s: Vec<CString>,
}

impl EchoResponse {
    pub fn to_c(&self) -> EchoResponseC {
        #[allow(unused_mut)]
        let mut h = EchoResponseC { c: unsafe { std::mem::zeroed() }, _s: Vec::new(),
        };
        { let cs = CString::new(self.echoed.as_str()).unwrap_or_default(); h.c.echoed = cs.as_ptr(); h._s.push(cs); }
        { let cs = CString::new(self.timer_name.as_str()).unwrap_or_default(); h.c.timer_name = cs.as_ptr(); h._s.push(cs); }
        h
    }
    pub fn from_c(c: &ffi::EchoResponse) -> Self {
        EchoResponse {
            echoed: cstr(c.echoed),
            timer_name: cstr(c.timer_name),
        }
    }
}

#[derive(Clone, Debug, Default)]
pub struct ComplexRequest {
    pub messages: Vec<EchoRequest>,
    pub tags: Vec<String>,
    pub note: Option<String>,
    pub retries: Option<i64>,
}

pub struct ComplexRequestC {
    pub c: ffi::ComplexRequest,
    _s: Vec<CString>,
    _a_messages: Vec<ffi::EchoRequest>,
    _h_messages: Vec<EchoRequestC>,
    _a_tags: Vec<*const c_char>,
}

impl ComplexRequest {
    pub fn to_c(&self) -> ComplexRequestC {
        #[allow(unused_mut)]
        let mut h = ComplexRequestC { c: unsafe { std::mem::zeroed() }, _s: Vec::new(),
            _a_messages: Vec::new(),
            _h_messages: Vec::new(),
            _a_tags: Vec::new(),
        };
        for x in &self.messages {
            let eh = x.to_c();
            h._a_messages.push(eh.c);
            h._h_messages.push(eh);
        }
        h.c.messages = if h._a_messages.is_empty() { std::ptr::null() } else { h._a_messages.as_ptr() };
        h.c.messages_len = h._a_messages.len();
        for x in &self.tags {
            let cs = CString::new(x.as_str()).unwrap_or_default();
            h._a_tags.push(cs.as_ptr());
            h._s.push(cs);
        }
        h.c.tags = if h._a_tags.is_empty() { std::ptr::null() } else { h._a_tags.as_ptr() };
        h.c.tags_len = h._a_tags.len();
        if let Some(x) = &self.note {
            let cs = CString::new(x.as_str()).unwrap_or_default();
            h.c.note = cs.as_ptr(); h.c.note_present = 1; h._s.push(cs);
        }
        if let Some(v) = self.retries { h.c.retries_present = 1; h.c.retries = v; }
        h
    }
    pub fn from_c(c: &ffi::ComplexRequest) -> Self {
        ComplexRequest {
            messages: if c.messages.is_null() { Vec::new() } else { unsafe { std::slice::from_raw_parts(c.messages, c.messages_len) }.iter().map(|e| EchoRequest::from_c(e)).collect() },
            tags: if c.tags.is_null() { Vec::new() } else { unsafe { std::slice::from_raw_parts(c.tags, c.tags_len) }.iter().map(|&p| cstr(p)).collect() },
            note: if c.note_present != 0 { Some(cstr(c.note)) } else { None },
            retries: if c.retries_present != 0 { Some(c.retries) } else { None },
        }
    }
}

#[derive(Clone, Debug, Default)]
pub struct ComplexResponse {
    pub summary: String,
    pub item_count: i64,
    pub has_note: bool,
}

pub struct ComplexResponseC {
    pub c: ffi::ComplexResponse,
    _s: Vec<CString>,
}

impl ComplexResponse {
    pub fn to_c(&self) -> ComplexResponseC {
        #[allow(unused_mut)]
        let mut h = ComplexResponseC { c: unsafe { std::mem::zeroed() }, _s: Vec::new(),
        };
        { let cs = CString::new(self.summary.as_str()).unwrap_or_default(); h.c.summary = cs.as_ptr(); h._s.push(cs); }
        h.c.item_count = self.item_count;
        h.c.has_note = if self.has_note { 1 } else { 0 };
        h
    }
    pub fn from_c(c: &ffi::ComplexResponse) -> Self {
        ComplexResponse {
            summary: cstr(c.summary),
            item_count: c.item_count,
            has_note: c.has_note != 0,
        }
    }
}

#[derive(Clone, Debug, Default)]
pub struct EchoEvent {
    pub message: String,
    pub echo_count: i64,
}

pub struct EchoEventC {
    pub c: ffi::EchoEvent,
    _s: Vec<CString>,
}

impl EchoEvent {
    pub fn to_c(&self) -> EchoEventC {
        #[allow(unused_mut)]
        let mut h = EchoEventC { c: unsafe { std::mem::zeroed() }, _s: Vec::new(),
        };
        { let cs = CString::new(self.message.as_str()).unwrap_or_default(); h.c.message = cs.as_ptr(); h._s.push(cs); }
        h.c.echo_count = self.echo_count;
        h
    }
    pub fn from_c(c: &ffi::EchoEvent) -> Self {
        EchoEvent {
            message: cstr(c.message),
            echo_count: c.echo_count,
        }
    }
}

#[derive(Clone, Debug, Default)]
pub struct JobSpec {
    pub name: String,
    pub payload: Vec<String>,
    pub priority: i64,
}

pub struct JobSpecC {
    pub c: ffi::JobSpec,
    _s: Vec<CString>,
    _a_payload: Vec<*const c_char>,
}

impl JobSpec {
    pub fn to_c(&self) -> JobSpecC {
        #[allow(unused_mut)]
        let mut h = JobSpecC { c: unsafe { std::mem::zeroed() }, _s: Vec::new(),
            _a_payload: Vec::new(),
        };
        { let cs = CString::new(self.name.as_str()).unwrap_or_default(); h.c.name = cs.as_ptr(); h._s.push(cs); }
        for x in &self.payload {
            let cs = CString::new(x.as_str()).unwrap_or_default();
            h._a_payload.push(cs.as_ptr());
            h._s.push(cs);
        }
        h.c.payload = if h._a_payload.is_empty() { std::ptr::null() } else { h._a_payload.as_ptr() };
        h.c.payload_len = h._a_payload.len();
        h.c.priority = self.priority;
        h
    }
    pub fn from_c(c: &ffi::JobSpec) -> Self {
        JobSpec {
            name: cstr(c.name),
            payload: if c.payload.is_null() { Vec::new() } else { unsafe { std::slice::from_raw_parts(c.payload, c.payload_len) }.iter().map(|&p| cstr(p)).collect() },
            priority: c.priority,
        }
    }
}

#[derive(Clone, Debug, Default)]
pub struct RetryPolicy {
    pub max_attempts: i64,
    pub backoff_ms: i64,
    pub retry_on: Vec<String>,
}

pub struct RetryPolicyC {
    pub c: ffi::RetryPolicy,
    _s: Vec<CString>,
    _a_retry_on: Vec<*const c_char>,
}

impl RetryPolicy {
    pub fn to_c(&self) -> RetryPolicyC {
        #[allow(unused_mut)]
        let mut h = RetryPolicyC { c: unsafe { std::mem::zeroed() }, _s: Vec::new(),
            _a_retry_on: Vec::new(),
        };
        h.c.max_attempts = self.max_attempts;
        h.c.backoff_ms = self.backoff_ms;
        for x in &self.retry_on {
            let cs = CString::new(x.as_str()).unwrap_or_default();
            h._a_retry_on.push(cs.as_ptr());
            h._s.push(cs);
        }
        h.c.retry_on = if h._a_retry_on.is_empty() { std::ptr::null() } else { h._a_retry_on.as_ptr() };
        h.c.retry_on_len = h._a_retry_on.len();
        h
    }
    pub fn from_c(c: &ffi::RetryPolicy) -> Self {
        RetryPolicy {
            max_attempts: c.max_attempts,
            backoff_ms: c.backoff_ms,
            retry_on: if c.retry_on.is_null() { Vec::new() } else { unsafe { std::slice::from_raw_parts(c.retry_on, c.retry_on_len) }.iter().map(|&p| cstr(p)).collect() },
        }
    }
}

#[derive(Clone, Debug, Default)]
pub struct ScheduleConfig {
    pub start_at_ms: i64,
    pub interval_ms: i64,
    pub jitter: Option<i64>,
}

pub struct ScheduleConfigC {
    pub c: ffi::ScheduleConfig,
    _s: Vec<CString>,
}

impl ScheduleConfig {
    pub fn to_c(&self) -> ScheduleConfigC {
        #[allow(unused_mut)]
        let mut h = ScheduleConfigC { c: unsafe { std::mem::zeroed() }, _s: Vec::new(),
        };
        h.c.start_at_ms = self.start_at_ms;
        h.c.interval_ms = self.interval_ms;
        if let Some(v) = self.jitter { h.c.jitter_present = 1; h.c.jitter = v; }
        h
    }
    pub fn from_c(c: &ffi::ScheduleConfig) -> Self {
        ScheduleConfig {
            start_at_ms: c.start_at_ms,
            interval_ms: c.interval_ms,
            jitter: if c.jitter_present != 0 { Some(c.jitter) } else { None },
        }
    }
}

#[derive(Clone, Debug, Default)]
pub struct ScheduleResult {
    pub job_id: String,
    pub will_run_count: i64,
    pub first_run_at_ms: i64,
    pub effective_backoff_ms: i64,
}

pub struct ScheduleResultC {
    pub c: ffi::ScheduleResult,
    _s: Vec<CString>,
}

impl ScheduleResult {
    pub fn to_c(&self) -> ScheduleResultC {
        #[allow(unused_mut)]
        let mut h = ScheduleResultC { c: unsafe { std::mem::zeroed() }, _s: Vec::new(),
        };
        { let cs = CString::new(self.job_id.as_str()).unwrap_or_default(); h.c.job_id = cs.as_ptr(); h._s.push(cs); }
        h.c.will_run_count = self.will_run_count;
        h.c.first_run_at_ms = self.first_run_at_ms;
        h.c.effective_backoff_ms = self.effective_backoff_ms;
        h
    }
    pub fn from_c(c: &ffi::ScheduleResult) -> Self {
        ScheduleResult {
            job_id: cstr(c.job_id),
            will_run_count: c.will_run_count,
            first_run_at_ms: c.first_run_at_ms,
            effective_backoff_ms: c.effective_backoff_ms,
        }
    }
}
