/* ============================================================
 * AUTO-GENERATED by nim-ffi v0.1.3  (ffiMode=raw, ffiLang=cpp). DO NOT EDIT.
 *
 *   Source:     ../aggregator.nim
 *   Generator:  ffi/codegen/c.nim
 *   Regenerate: nimble genbindings_cpp_rawc
 * ============================================================ */

#pragma once

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ----------------------------------------------------------------------------
 * FFI callback type.
 *
 * Used as the success/failure notification for every async call. Identical
 * to the Nim `FFICallBack` signature byte-for-byte; reused unchanged by the
 * C++ sugar layer.
 *
 *   ret      : 0 = OK, 1 = error, 2 = missing callback
 *   msg      : on RET_OK, points to a `const <Proc>Resp*` (caller must cast).
 *              On RET_ERR, points to a UTF-8 error message of `len` bytes
 *              (not necessarily NUL-terminated).
 *   len      : on RET_OK, sizeof of the Resp struct. On RET_ERR, byte length
 *              of the error string.
 *   user_data: pass-through pointer the caller supplied at the call site.
 *
 * Lifetime: any pointer reachable from `msg` (the Resp struct, any
 * `const char*` field inside it, etc.) is valid only for the duration of
 * the callback invocation. Deep-copy anything you want to retain.
 * -------------------------------------------------------------------------- */
typedef void (*FfiCallback)(int ret, const char* msg, size_t len, void* user_data);


/* ============================================================
 * User-declared FFI types
 * ============================================================ */

typedef struct AggregatorConfig {
    const char* prefix;
} AggregatorConfig;

typedef struct RecordRequest {
    const char* entry;
} RecordRequest;

typedef struct RecordResponse {
    int64_t index;
    int64_t count;
    const char* prefix;
} RecordResponse;

typedef struct SummarizeResponse {
    int64_t count;
    const char** entries;
    size_t entries_len;
    const char* prefix;
} SummarizeResponse;

/* ============================================================
 * Per-proc request envelopes
 * ============================================================ */

typedef struct AggregatorCreateCtorReq {
    AggregatorConfig config;
} AggregatorCreateCtorReq;

typedef struct AggregatorRecordReq {
    RecordRequest req;
} AggregatorRecordReq;

typedef struct AggregatorSummarizeReq {
    uint8_t _placeholder;
} AggregatorSummarizeReq;

/* ============================================================
 * Per-proc response envelopes
 * (delivered through the FfiCallback's `msg` pointer)
 * ============================================================ */

typedef struct AggregatorRecordResp {
    RecordResponse value;
} AggregatorRecordResp;

typedef struct AggregatorSummarizeResp {
    SummarizeResponse value;
} AggregatorSummarizeResp;

/* ============================================================
 * Function declarations
 *
 * Procs with a `_v<hash>` suffix are content-addressed: changing
 * the canonical signature (param/return types, transitive {.ffi.}
 * type fields) changes the hash and therefore the symbol name.
 * Stale consumers fail to link with a loud `undefined symbol`
 * error rather than silently reading mismatched layouts.
 * ============================================================ */

void* aggregator_create_v4b5b607(const AggregatorCreateCtorReq* req, FfiCallback cb, void* user_data);
#define aggregator_create aggregator_create_v4b5b607
int aggregator_record_v95994e6(void* ctx, FfiCallback cb, void* user_data, const AggregatorRecordReq* req);
#define aggregator_record aggregator_record_v95994e6
int aggregator_summarize_v5f3558e(void* ctx, FfiCallback cb, void* user_data, const AggregatorSummarizeReq* req);
#define aggregator_summarize aggregator_summarize_v5f3558e
int aggregator_destroy(void* ctx);

#ifdef __cplusplus
} /* extern "C" */
#endif
