/* ============================================================
 * AUTO-GENERATED by nim-ffi v0.1.3  (ffiMode=raw, ffiLang=cpp). DO NOT EDIT.
 *
 *   Source:     ../timer.nim
 *   Generator:  ffi/codegen/c.nim
 *   Regenerate: nimble genbindings_cpp_rawc
 * ============================================================ */

#pragma once

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ----------------------------------------------------------------------------
 * FFI callback type.
 *
 * Used as the success/failure notification for every async call. Identical
 * to the Nim `FFICallBack` signature byte-for-byte; reused unchanged by the
 * C++ sugar layer.
 *
 *   ret      : 0 = OK, 1 = error, 2 = missing callback
 *   msg      : on RET_OK, points to a `const <Proc>Resp*` (caller must cast).
 *              On RET_ERR, points to a UTF-8 error message of `len` bytes
 *              (not necessarily NUL-terminated).
 *   len      : on RET_OK, sizeof of the Resp struct. On RET_ERR, byte length
 *              of the error string.
 *   user_data: pass-through pointer the caller supplied at the call site.
 *
 * Lifetime: any pointer reachable from `msg` (the Resp struct, any
 * `const char*` field inside it, etc.) is valid only for the duration of
 * the callback invocation. Deep-copy anything you want to retain.
 * -------------------------------------------------------------------------- */
typedef void (*FfiCallback)(int ret, const char* msg, size_t len, void* user_data);


/* ============================================================
 * User-declared FFI types
 * ============================================================ */

typedef struct TimerConfig {
    const char* name;
} TimerConfig;

typedef struct EchoRequest {
    const char* message;
    int64_t delayMs;
} EchoRequest;

typedef struct EchoResponse {
    const char* echoed;
    const char* timerName;
} EchoResponse;

typedef struct ComplexRequest {
    const EchoRequest* messages;
    size_t messages_len;
    const char** tags;
    size_t tags_len;
    const char** note;
    const int64_t* retries;
} ComplexRequest;

typedef struct ComplexResponse {
    const char* summary;
    int64_t itemCount;
    bool hasNote;
} ComplexResponse;

typedef struct JobSpec {
    const char* name;
    const char** payload;
    size_t payload_len;
    int64_t priority;
} JobSpec;

typedef struct RetryPolicy {
    int64_t maxAttempts;
    int64_t backoffMs;
    const char** retryOn;
    size_t retryOn_len;
} RetryPolicy;

typedef struct ScheduleConfig {
    int64_t startAtMs;
    int64_t intervalMs;
    const int64_t* jitter;
} ScheduleConfig;

typedef struct ScheduleResult {
    const char* jobId;
    int64_t willRunCount;
    int64_t firstRunAtMs;
    int64_t effectiveBackoffMs;
} ScheduleResult;

/* ============================================================
 * Per-proc request envelopes
 * ============================================================ */

typedef struct MyTimerCreateCtorReq {
    TimerConfig config;
} MyTimerCreateCtorReq;

typedef struct MyTimerEchoReq {
    EchoRequest req;
} MyTimerEchoReq;

typedef struct MyTimerVersionReq {
    uint8_t _placeholder;
} MyTimerVersionReq;

typedef struct MyTimerComplexReq {
    ComplexRequest req;
} MyTimerComplexReq;

typedef struct MyTimerScheduleReq {
    JobSpec job;
    RetryPolicy retry;
    ScheduleConfig schedule;
} MyTimerScheduleReq;

/* ============================================================
 * Per-proc response envelopes
 * (delivered through the FfiCallback's `msg` pointer)
 * ============================================================ */

typedef struct MyTimerEchoResp {
    EchoResponse value;
} MyTimerEchoResp;

typedef struct MyTimerVersionResp {
    const char* value;
} MyTimerVersionResp;

typedef struct MyTimerComplexResp {
    ComplexResponse value;
} MyTimerComplexResp;

typedef struct MyTimerScheduleResp {
    ScheduleResult value;
} MyTimerScheduleResp;

/* ============================================================
 * Function declarations
 *
 * Procs with a `_v<hash>` suffix are content-addressed: changing
 * the canonical signature (param/return types, transitive {.ffi.}
 * type fields) changes the hash and therefore the symbol name.
 * Stale consumers fail to link with a loud `undefined symbol`
 * error rather than silently reading mismatched layouts.
 * ============================================================ */

void* my_timer_create_v1d3b827(const MyTimerCreateCtorReq* req, FfiCallback cb, void* user_data);
#define my_timer_create my_timer_create_v1d3b827
int my_timer_echo_vbfc3452(void* ctx, FfiCallback cb, void* user_data, const MyTimerEchoReq* req);
#define my_timer_echo my_timer_echo_vbfc3452
int my_timer_version_v31daa50(void* ctx, FfiCallback cb, void* user_data, const MyTimerVersionReq* req);
#define my_timer_version my_timer_version_v31daa50
int my_timer_complex_v4d2cf2b(void* ctx, FfiCallback cb, void* user_data, const MyTimerComplexReq* req);
#define my_timer_complex my_timer_complex_v4d2cf2b
int my_timer_schedule_v7365fe1(void* ctx, FfiCallback cb, void* user_data, const MyTimerScheduleReq* req);
#define my_timer_schedule my_timer_schedule_v7365fe1
int my_timer_destroy(void* ctx);

#ifdef __cplusplus
} /* extern "C" */
#endif
