// Code generated by nim-ffi Go codegen. DO NOT EDIT.
package host_demo

/*
#cgo CFLAGS: -I${SRCDIR}
#cgo LDFLAGS: -L${SRCDIR} -lhost_demo -Wl,-rpath,${SRCDIR}
#include "host_demo.h"
#include <stdlib.h>
#include <string.h>
#include <pthread.h>

extern void host_demoGoEvent(int ret, char* msg, size_t len, void* userData);
extern void host_demoHostTrampoline(uint64_t callId, char* req, size_t reqLen, void* userData);
static int host_demoRegisterHost(void* ctx, const char* name, void* ud) {
  return host_demo_register_host_fn(ctx, name, (FFIHostFn)host_demoHostTrampoline, ud);
}

typedef struct {
  int ret; char* msg; size_t len; int done;
  pthread_mutex_t mu; pthread_cond_t cv;
} Host_demoResp;

static Host_demoResp* host_demoRespNew() {
  Host_demoResp* r = (Host_demoResp*)calloc(1, sizeof(Host_demoResp));
  pthread_mutex_init(&r->mu, NULL); pthread_cond_init(&r->cv, NULL);
  return r;
}
static void host_demoRespFree(Host_demoResp* r) {
  if (!r) return;
  if (r->msg) free(r->msg);
  pthread_mutex_destroy(&r->mu); pthread_cond_destroy(&r->cv); free(r);
}
static int host_demoRespRet(Host_demoResp* r) { return r->ret; }
static char* host_demoRespMsg(Host_demoResp* r) { return r->msg; }
static size_t host_demoRespLen(Host_demoResp* r) { return r->len; }

static void host_demoRespCb(int ret, const char* msg, size_t len, void* ud) {
  Host_demoResp* r = (Host_demoResp*)ud;
  pthread_mutex_lock(&r->mu);
  r->ret = ret;
  // Native ABI: (msg, len) is the raw result (RET_OK) or error (RET_ERR).
  // Copy it so it survives past the callback.
  char* e = (char*)malloc(len + 1); if (e) { memcpy(e, msg, len); e[len] = 0; }
  r->msg = e; r->len = len;
  r->done = 1; pthread_cond_signal(&r->cv); pthread_mutex_unlock(&r->mu);
}
static void host_demoRespWait(Host_demoResp* r) {
  pthread_mutex_lock(&r->mu);
  while (!r->done) pthread_cond_wait(&r->cv, &r->mu);
  pthread_mutex_unlock(&r->mu);
}

static void* host_demoCall_demo_create(Host_demoResp* r) {
  void* ctx = demo_create(host_demoRespCb, r);
  host_demoRespWait(r);
  return ctx;
}
static int host_demoCall_use_token(void* ctx, const char* key, Host_demoResp* r) {
  int rc = use_token(ctx, host_demoRespCb, r, key);
  if (rc == RET_OK) host_demoRespWait(r);
  return rc;
}
static int host_demoCall_demo_destroy(void* ctx) { return demo_destroy(ctx); }
static uint64_t host_demoRegisterEvents(void* ctx) { return host_demo_add_event_listener(ctx, "", (FFICallBack)host_demoGoEvent, ctx); }
*/
import "C"

import (
	"errors"
	"runtime/cgo"
	"sync"
	"unsafe"
)

type resultSlot struct {
	val  any
	err  error
	done chan struct{}
}

type Host_demoNode struct {
	ctx unsafe.Pointer
}

// goStr extracts and frees the captured response string.
func respStr(r *C.Host_demoResp) string {
	return C.GoStringN(C.host_demoRespMsg(r), C.int(C.host_demoRespLen(r)))
}

var (
	eventMu      sync.Mutex
	eventHandler func(string)
)

// SetEventHandler installs the catch-all handler for library-initiated
// events (delivered as raw JSON strings).
func (n *Host_demoNode) SetEventHandler(h func(string)) {
	eventMu.Lock()
	eventHandler = h
	eventMu.Unlock()
	C.host_demoRegisterEvents(n.ctx)
}

//export host_demoGoEvent
func host_demoGoEvent(ret C.int, msg *C.char, length C.size_t, userData unsafe.Pointer) {
	eventMu.Lock()
	h := eventHandler
	eventMu.Unlock()
	if h != nil && ret == C.RET_OK {
		h(C.GoStringN(msg, C.int(length)))
	}
}

type hostEntry struct {
	ctx unsafe.Pointer
	fn  func(string) (string, error)
}

//export host_demoHostTrampoline
func host_demoHostTrampoline(callId C.uint64_t, req *C.char, reqLen C.size_t, userData unsafe.Pointer) {
	e := cgo.Handle(uintptr(userData)).Value().(hostEntry)
	reqStr := C.GoStringN(req, C.int(reqLen))
	go func() {
		res, err := e.fn(reqStr)
		if err != nil {
			msg := err.Error()
			cmsg := C.CString(msg)
			C.host_demo_host_complete(e.ctx, callId, C.int(C.RET_ERR), cmsg, C.size_t(len(msg)))
			C.free(unsafe.Pointer(cmsg))
		} else {
			cmsg := C.CString(res)
			C.host_demo_host_complete(e.ctx, callId, C.int(C.RET_OK), cmsg, C.size_t(len(res)))
			C.free(unsafe.Pointer(cmsg))
		}
	}()
}

// SetFetchToken registers the host implementation of the 'fetch_token' {.ffiHost.} call.
func (n *Host_demoNode) SetFetchToken(fn func(string) (string, error)) {
	handle := cgo.NewHandle(hostEntry{ctx: n.ctx, fn: fn})
	cname := C.CString("fetch_token")
	C.host_demoRegisterHost(n.ctx, cname, unsafe.Pointer(handle))
	C.free(unsafe.Pointer(cname))
}

func NewHost_demo() (*Host_demoNode, error) {
	r := C.host_demoRespNew()
	defer C.host_demoRespFree(r)
	ctx := C.host_demoCall_demo_create(r)
	if C.host_demoRespRet(r) != C.RET_OK {
		return nil, errors.New(respStr(r))
	}
	return &Host_demoNode{ctx: ctx}, nil
}

func (n *Host_demoNode) UseToken(key string) (string, error) {
	c_key := C.CString(key)
	defer C.free(unsafe.Pointer(c_key))
	r := C.host_demoRespNew()
	defer C.host_demoRespFree(r)
	C.host_demoCall_use_token(n.ctx, c_key, r)
	if C.host_demoRespRet(r) != C.RET_OK {
		return "", errors.New(respStr(r))
	}
	return respStr(r), nil
}

func (n *Host_demoNode) Destroy() error {
	if C.host_demoCall_demo_destroy(n.ctx) != C.RET_OK {
		return errors.New("host_demo destroy failed")
	}
	return nil
}
